[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Compiler flags for optimization
build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=1
    -fmax-errors=5

; Libraries
lib_deps =
    adafruit/Adafruit PN532@^1.2.2
    adafruit/Adafruit SSD1306@^2.5.7
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
    adafruit/Adafruit NeoPixel@^1.12.0
    bblanchon/ArduinoJson@^6.21.2
    https://github.com/tzapu/WiFiManager.git

; Serial monitor settings
monitor_filters = esp32_exception_decoder
